### ISSUE TITLE
json error

### ISSUE THREAD

**Issue by louwenjjr** [omigami/omigami#19]
Hi, I was trying out the API (using Justin's key) and ran across this issue while using the mgf file from the example notebook.

I'm using python 3.7 and installed (latest version from 11-06) of omigami with pip in a conda environment.

Command I used:
`
spectra_matches = spec2vec.match_spectra_from_path(mgf_path = path_to_mgf, n_best = 10)
`
Error:
`
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/mnt/scratch/louwe015/miniconda3/envs/omigami/lib/python3.7/site-packages/omigami/spec2vec.py", line 78, in match_spectra_from_path
predictions.extend(self._format_results(r))
File "/mnt/scratch/louwe015/miniconda3/envs/omigami/lib/python3.7/site-packages/omigami/spec2vec.py", line 181, in _format_results
response = json.loads(api_request.text)
File "/mnt/scratch/louwe015/miniconda3/envs/omigami/lib/python3.7/json/__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "/mnt/scratch/louwe015/miniconda3/envs/omigami/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/mnt/scratch/louwe015/miniconda3/envs/omigami/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

Thanks in advance for the help and let me know if I missed something causing this error.

**Comment by carloszanella** [comment]
Hi @louwenjjr , I reproduced this issue and realised that it happened because the service was down. I restarted it and it is back up. I am also updating the notebook/readme in a PR.

https://github.com/omigami/omigami/pull/21
