### ISSUE TITLE
KeyError when pepmass is not present in metadata

### ISSUE THREAD

**Issue by louwenjjr** [omigami/omigami#20]
Hi, I was trying out the API (using Justin's key) and ran across an issue while using some mgf file that I created from some spectra (read from json) and saved as mgf using matchms.exporting.save_as_mgf. Apparently, this matchms function does not save pepmass in the mgf and therefore raises a keyerror in the api. Maybe it is worthwhile to add some error handling/skip that spectrum or to look for "precursor_mz" in the metadata if "pepmass" does not exist?

I'm using python 3.7 and installed (latest version from 11-06) of omigami with pip in a conda environment.

Command used:
`
spectra_matches = spec2vec.match_spectra_from_path(mgf_path = test_mgf, n_best = 10)
`
Error:
`
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/mnt/scratch/louwe015/miniconda3/envs/omigami/lib/python3.7/site-packages/omigami/spec2vec.py", line 73, in match_spectra_from_path
payload = self._build_payload(batch, parameters)
File "/mnt/scratch/louwe015/miniconda3/envs/omigami/lib/python3.7/site-packages/omigami/spec2vec.py", line 105, in _build_payload
"Precursor_MZ": str(spectrum.metadata["pepmass"][0]),
KeyError: 'pepmass'
`

Thanks!

**Comment by carloszanella** [comment]
hi @louwenjjr , thanks for the suggestion. Is this something that can happen often: not have the `pepmass` field but a `precursor_mz` field?

We can look for the other key. Can you send a small example of a mgf file with a spectrum without pepmass so I can reproduce it here and test if the changes work correctly?
